name: Deploy to Server

on:
  push:
    branches:
      - main # main 브랜치에 푸시할 때만 실행

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        id: deploy-server
        if: contains(github.ref, 'main')
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          envs: GITHUB_SHA
          script: |
            sudo docker ps
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/bangbangbang
            sudo docker run -d -p 5555:5555 ${{ secrets.DOCKER_USRENAME }}/bangbangbang
            sudo docker image prune -f

      # - name: Build and Push Docker Image
      #   run: |
      #     docker build -t doughnutdough5/bangbangbang:latest .
      #     docker push doughnutdough5/bangbangbang:latest

      # - name: Deploy to Server
      #   run: |
      #     ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_HOST }} << 'EOF'
      #       docker pull doughnutdough5/bangbangbang:latest
      #       docker stop your-app || true
      #       docker rm your-app || true
      #       docker run -d --name bangbangbang -p 5555:3000 doughnutdough5/bangbangbang:latest
      #     EOF
      #   env:
      #     SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
